# pull official base image
FROM node:lts-alpine3.15 AS builder

# set working directory
WORKDIR /home/node/app

# install app dependencies
#copies package.json and package-lock.json to Docker environment
COPY app/package.json ./

# Installs all node packages
RUN npm install 

# Copies everything over to Docker environment
COPY app ./
RUN npm run build

#Stage 2
#######################################
#pull the official nginx:1.23.3 base image
FROM nginx:1.23.3
#copies React to the container directory
# Set working directory to nginx resources directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=builder /home/node/app/build .
# Containers run nginx with global directives and daemon off
ENTRYPOINT ["nginx", "-g", "daemon off;"]